# Generated by Django 5.1.7 on 2025-04-22 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='Domain of the computer', max_length=255)),
                ('manufacturer', models.CharField(help_text='Manufacturer of the computer', max_length=255)),
                ('model', models.CharField(help_text='Model of the computer', max_length=255)),
                ('name', models.CharField(help_text='Computer name', max_length=255)),
                ('total_physical_memory', models.FloatField(help_text='Total physical memory in GB')),
                ('primaryowner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='computer_systems', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_directory', models.CharField(max_length=243)),
                ('organization', models.CharField(max_length=234)),
                ('build_number', models.IntegerField()),
                ('serial_number', models.CharField(max_length=400)),
                ('version', models.CharField(max_length=255)),
                ('registered_users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operating_systems', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_usage', models.FloatField(help_text='Percentage of CPU usage')),
                ('memory_usage', models.FloatField(help_text='Percentage of memory usage')),
                ('disk_usage', models.FloatField(help_text='Percentage of disk usage')),
                ('network_bandwidth', models.FloatField(help_text='Network bandwidth usage in Mbps')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_usages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
