# Generated by Django 5.2 on 2025-04-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='description',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the user account', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='client_id',
            field=models.CharField(blank=True, db_index=True, help_text='OAuth2 Client ID for this user', max_length=100, null=True, unique=True),
        ),
    ]
