# Generated by Django 5.2.1 on 2025-06-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_client_full_name_client_user_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="password_changed",
            field=models.BooleanField(default=False),
        ),
    ]
