# Generated by Django 5.1.7 on 2025-04-30 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FirewallStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField()),
                ('profile', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firewall_status', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['client', 'timestamp'], name='core_firewa_client__156097_idx'), models.Index(fields=['is_enabled'], name='core_firewa_is_enab_e04b2c_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('time_created', models.DateTimeField()),
                ('description', models.TextField()),
                ('source', models.CharField(default='Security', max_length=50)),
                ('logon_type', models.CharField(blank=True, max_length=50, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('target_account', models.CharField(blank=True, max_length=255, null=True)),
                ('group_name', models.CharField(blank=True, max_length=255, null=True)),
                ('privilege_name', models.CharField(blank=True, max_length=255, null=True)),
                ('process_name', models.CharField(blank=True, max_length=255, null=True)),
                ('service_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time_created'],
                'indexes': [models.Index(fields=['client', 'time_created'], name='core_securi_client__90ec5a_idx'), models.Index(fields=['event_id'], name='core_securi_event_i_d88976_idx'), models.Index(fields=['source'], name='core_securi_source_892cc2_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=255)),
                ('os_version', models.CharField(max_length=100)),
                ('processor_count', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('is_64bit', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['client', 'timestamp'], name='core_server_client__c435bf_idx'), models.Index(fields=['machine_name'], name='core_server_machine_af3f46_idx')],
            },
        ),
    ]
