# Generated by Django 5.2.1 on 2025-06-02 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_client_full_name_client_user_email_and_more"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnvironmentInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("os_version", models.CharField(max_length=100)),
                ("machine_name", models.CharField(max_length=100)),
                ("processor_count", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="FileLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=100)),
                ("path", models.CharField(max_length=255)),
                ("change_type", models.CharField(max_length=50)),
                ("old_path", models.CharField(blank=True, max_length=255)),
                ("timestamp", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="NetworkLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("local_address", models.CharField(max_length=100)),
                ("remote_address", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="ProcessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("pid", models.IntegerField()),
                ("path", models.CharField(max_length=255)),
                ("start_time", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="UserAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("domain", models.CharField(max_length=100)),
                ("sid", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="UserGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("groups", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="UserProfileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profile_path", models.CharField(max_length=255)),
                ("roaming_profile", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.IntegerField()),
                ("start_time", models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name="firewallstatus",
            name="client",
        ),
        migrations.RemoveField(
            model_name="serverinfo",
            name="client",
        ),
        migrations.RenameField(
            model_name="securityevent",
            old_name="description",
            new_name="details",
        ),
        migrations.RenameField(
            model_name="securityevent",
            old_name="time_created",
            new_name="timestamp",
        ),
        migrations.RemoveField(
            model_name="securityevent",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="securityevent",
            name="failure_reason",
        ),
        migrations.RemoveField(
            model_name="securityevent",
            name="group_name",
        ),
        migrations.RemoveField(
            model_name="securityevent",
            name="logon_type",
        ),
        migrations.RemoveField(
            model_name="securityevent",
            name="privilege_name",
        ),
        migrations.RemoveField(
            model_name="securityevent",
            name="process_name",
        ),
        migrations.RemoveField(
            model_name="securityevent",
            name="service_name",
        ),
        migrations.RemoveField(
            model_name="securityevent",
            name="target_account",
        ),
        migrations.AddField(
            model_name="securityevent",
            name="event_type",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="securityevent",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.client"
            ),
        ),
        migrations.AlterField(
            model_name="securityevent",
            name="event_id",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="securityevent",
            name="source",
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name="securityevent",
            index=models.Index(
                fields=["client", "timestamp"], name="core_securi_client__65d979_idx"
            ),
        ),
        migrations.AddField(
            model_name="environmentinfo",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.client"
            ),
        ),
        migrations.AddField(
            model_name="filelog",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.client"
            ),
        ),
        migrations.AddField(
            model_name="networklog",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.client"
            ),
        ),
        migrations.AddField(
            model_name="processlog",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.client"
            ),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.client"
            ),
        ),
        migrations.AddField(
            model_name="usergroup",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.client"
            ),
        ),
        migrations.AddField(
            model_name="userprofilemodel",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.client"
            ),
        ),
        migrations.AddField(
            model_name="usersession",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.client"
            ),
        ),
        migrations.DeleteModel(
            name="FirewallStatus",
        ),
        migrations.DeleteModel(
            name="ServerInfo",
        ),
        migrations.AddIndex(
            model_name="filelog",
            index=models.Index(
                fields=["client", "timestamp"], name="core_filelo_client__58224a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="networklog",
            index=models.Index(
                fields=["client", "timestamp"], name="core_networ_client__a078f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="processlog",
            index=models.Index(
                fields=["client", "start_time"], name="core_proces_client__3d4306_idx"
            ),
        ),
    ]
